version: "3"
services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      container_name: namenode
      command:  ["hdfs", "namenode"]
      ports:
        - 9870:9870
        - 9000:9000
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode:
      image: apache/hadoop:3
      container_name: datanode
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
   resourcemanager:
      image: apache/hadoop:3
      container_name: resourcemanager
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/test.sh
   nodemanager:
      image: apache/hadoop:3
      container_name: nodemanager
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
   spark:
      image: bde2020/spark-master:latest
      container_name: spark
      tty: true
      volumes:
        - /home/amine/hadoop:/hadoop-conf
   flume:
      image: anchorfree/flume:latest
      container_name: flume
      volumes:
        - ./flume-conf:/app/conf
        - /home/amine/hadoop:/hadoop-conf
        - /home/amine/classpath:/classpath
      ports:
        - 44444:44444
      command: ["flume-ng", "agent", "--name", "a1", "--conf", "/app/conf", "--conf-file", "/app/conf/flume2.conf"]
   zookeeper:
      image: ubuntu/zookeeper:latest
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zookeeper:2888:3888
      networks:
        - kafka
   kafka:
      image: ubuntu/kafka:latest
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      networks:
        - kafka

networks:
  kafka:
    driver: bridge